# Generated by Django 5.0.3 on 2024-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10)),
                ('slocation', models.CharField(max_length=10)),
                ('sprincipal', models.CharField(max_length=10)),
                ('sstrength', models.IntegerField()),
            ],
        ),
    ]
